Fix grammar in README
tokopedia/gripmock pull request #60
Opened 2020-11-03 02:40 UTC by yonasstephen

2021-01-06 21:26 UTC, damienhollis requested changes
One minor typo

2021-01-06 21:26 UTC, damienhollis commented on Readme.md
> +First, prepare your `.proto` file. oOr you can use `hello.proto` in `example/pb/` folder. Suppose you put it in `/mypath/hello.proto`. We are gonna use Docker image for easier example test.
Typo `oOr` should be `Or`

2021-01-11 12:54 UTC, yonasstephen commented on Readme.md
> +First, prepare your `.proto` file. oOr you can use `hello.proto` in `example/pb/` folder. Suppose you put it in `/mypath/hello.proto`. We are gonna use Docker image for easier example test.
Fixed.

2021-02-15 03:33 UTC, jekiapp commented on Readme.md
> +GripMock is a **mock server** for **GRPC** services. It's using a `.proto` file to generate implementation of gRPC service for you.
it can be more than one

2021-02-15 03:36 UTC, jekiapp approved these changes

2021-03-03 07:21 UTC, merged